from gsam_wrapper import GSAM2
from cotracker_wrapper import Cotracker3
from taxposed_data_collector import TaxPoseDDataCollector, plot_pcd
import torch
import argparse
import os
import numpy as np
from pathlib import Path
from tqdm import tqdm
import gc
from pyk4a import PyK4APlayback, PyK4ACapture
from pyk4a.calibration import CalibrationType, Calibration
import subprocess
import cv2

class VideoToTaxposed:
    """
    Assumptions:
    1. The input path contains a video in mk4 format, containing rgb, depth and intrinsics information. This can be captured e.g. using the module PyK4A (see capture_video.py)
    """
    def __init__(self,
                 input_path, # "assets/videos/table_bussing_four_objects"
                 output_path, # "assets/data/table_bussing_four_objects"
                 video_name="video",
                 object_names="mug.", # "blue plate. pink plate. red bowl. white cup"
                 num_objects=1, # mug
                 device="cuda:1",
                 vis_threshold=1.,
                 icp=False,
                 just_final=False,
                 debug=False):
        """ Initialize the VideoToTaxposed class.
            Args:
                input_path (str): Path to the input video directory and subsequent data generated by the class if in debug mode
                output_path (str): Path where the output data will be saved
                video_name (str, optional): Name of the mkv video file.
                object_names (str, optional): Space-separated string containing object names to track. Each name should end with period. Defaults to "mug."
                num_objects (int, optional): Number of objects to track. Defaults to 1
                device (str, optional): Device to run computations on. Defaults to "cuda:1"
                debug (bool, optional): Enable debug mode. Defaults to False
            Attributes:
                vis_threshold (float): Maximum distance (in meters) threshold for point visibility. Points further than this distance from camera are removed
            Note:
                The object_names string should have exactly num_objects names, each ending with a period.
                Example: "blue plate. pink plate. red bowl." for num_objects=3
        """
        self.input_path = input_path
        self.output_path = output_path
        self.video_name = video_name
        self.object_names = object_names
        self.num_objects = num_objects
        self.device = device
        self.icp = icp
        self.just_final = just_final
        self.debug = debug
        self.vis_threshold = vis_threshold # All points further than this distance from the camera are removed

        self.gsam2 = GSAM2(self.device,
                   output_dir=Path(self.output_path),
                   debug=self.debug)
        self.cotracker3 = Cotracker3(self.device)
        self.data_collector = TaxPoseDDataCollector(self.output_path, self.debug)


    def _mkv_to_point_cloud_sequence(self):
        """
        Convert an MKV video file captured from a Kinect v4 camera into a sequence of point clouds.

        This method processes a recorded MKV video file frame by frame, extracting the depth
        information from each frame to generate 3D point clouds. The point clouds 
        are stored sequentially in a numpy array.

        Returns:
            np.ndarray: A sequence of point clouds, where each point cloud contains 3D coordinates
                   for each point. Shape is (height, width, n_points, 3), where the
                   last dimension contains [x, y, z] values.
        Raises:
            EOFError: When reaching the end of the video file.

        Note:
            - The input MKV file must be located at self.input_path/self.video_name
            - Frames where depth data is missing are skipped
            - Points beyond self.vis_threshold meters from camera are filtered out
        """
        pcd_sequence = []
        k4a = PyK4APlayback(self.input_path + "/" + self.video_name + ".mkv")
        k4a.open()
        
        try:
            while True:
                # Get next frame
                capture = k4a.get_next_capture()
                
                # Skip frames with missing data
                if capture.depth is None or capture.color is None:
                    continue

                # Convert depth image to 3D points
                points_3d = capture.transformed_depth_point_cloud

                # Convert points from millimeters to meters
                points_3d = points_3d.astype(np.float32) / 1e3          # Convert to meters

                # Remove invalid points (where depth is 0 or beyond threshold)
                valid_points = np.logical_and(points_3d[:, :, 2] > 0, points_3d[:, :, 2] < self.vis_threshold)
                points_3d[~valid_points] = 0
                
                # colors = capture.color.reshape(-1, 3).astype(float) / 255.0
                
                # Create point cloud with xyz and rgb values
                # point_cloud = np.concatenate([points_3d, colors], axis=1)
                point_cloud = points_3d
                pcd_sequence.append(point_cloud)
            
        except EOFError:
            print("Reached end of video file")
        finally:
            k4a.close()
            
        return np.array(pcd_sequence)
    
    def _mkv_to_mp4(self):
        """
        Convert an MKV video file to MP4 format using FFmpeg.

        This method uses FFmpeg to convert the input MKV video file to MP4 format while preserving
        the video stream and using the H.264 codec. The output file will be saved in the same
        directory as the input file.

        Returns:
            None

        Raises:
            subprocess.CalledProcessError: If the FFmpeg conversion process fails.

        Note:
            - Requires FFmpeg to be installed on the system
            - Only copies the video stream (stream 0:0) and ignores audio tracks
            - Output filename will have the same name as input but with .mp4 extension
        """
        input_path = self.input_path + "/" + self.video_name + ".mkv"
        output_path = self.input_path + "/" + self.video_name + ".mp4"

        # if self.debug:
        #     command = ['ffmpeg', '-i', input_path, '-map', '0:0', '-c:v', 'libx264', output_path]   
        # else:
        #     command = ['ffmpeg', '-y', '-hide_banner', '-loglevel', 'error', '-i', input_path, '-map', '0:0', '-c:v', 'libx264', output_path]

        command = ['ffmpeg', '-y', '-hide_banner', '-loglevel', 'error', '-i', input_path, '-map', '0:0', '-c:v', 'libx264', output_path]
        subprocess.run(command, check=True)

    def _process_object_tracks(self):
        """
        This method takes a video and object information to generate object tracks. It uses GSAM for mask 
        generation and Cotracker for tracking objects throughout the video sequence.

        Parameters
        ----------
        None : Uses instance attributes
            self.input_path : str
                Path to input directory
            self.video_name : str
                Name of the video file
            self.debug : bool
                Flag for debug mode
            self.object_names : list
                Names of objects to track
            self.frame : int
                Frame number to process
            self.num_objects : int
                Number of objects to track
            self.device : str
                Device to run inference on ('cpu' or 'cuda')

        Returns
        -------
        list
            List of numpy arrays containing predicted tracks for each object.
            Each track array has shape (num_frames, num_points, 2) containing xy coordinates.

        Notes
        -----
        If debug mode is enabled, tracks will be saved in the input directory under 'tracks_' folder.
        """
        mp4_video_path = self.input_path + "/" + self.video_name + ".mp4"
        if self.debug:
            tracks_path = self.input_path
            os.makedirs(tracks_path, exist_ok=True)

        # GSAM inference
        masks, scores, logits, confidences, labels, input_boxes = self.gsam2.get_masks_video(self.object_names, mp4_video_path, 0)
        filtered_masks, _ = self.gsam2.filter_masks(masks, labels, self.num_objects)

        # Cotracker inference
        all_tracks = []
        filtered_masks = filtered_masks[:, 0]
        for i in range(filtered_masks.shape[0]):
            pred_tracks = self.cotracker3.get_tracks(mp4_video_path, filtered_masks[i])
            if self.debug:
                aux_pred_tracks = pred_tracks.unsqueeze(0)
                self.cotracker3.visualize(mp4_video_path, aux_pred_tracks, output_path=self.input_path, filename = "video_cotracker")
            pred_tracks = pred_tracks.cpu().detach().numpy()
            if self.debug:
                np.save(tracks_path + "/" + "tracks" + ".npy", pred_tracks)                
            all_tracks.append(pred_tracks)
        return all_tracks

    def main_non_icp(self):
        """
        Main pipeline for processing video data without using ICP (Iterative Closest Point) algorithm.
        The method performs the following steps:
        1. Converts MKV video to MP4 format
        2. Generates point cloud sequence from MP4 video
        3. Processes object tracks from the video
        4. Runs GSAM inference to get object masks from the first frame
        5. Prepares initial point cloud with segmentation
        6. Detects object movement in the video
        7. Computes transform sequences
        8. Saves processed data for training
        Returns:
            None
        Side Effects:
            - Creates MP4 file from MKV
            - Saves masks as PNG and NPY files if debug mode is enabled
            - Saves final processed data including point clouds and transforms
        Debug Mode Features:
            When self.debug is True, provides verbose output and visualization at each step:
            - Prints progress messages
            - Visualizes GSAM masks
            - Plots point clouds
            - Saves intermediate results
        """

        # Convert MKV to MP4
        if self.debug:
            print("Converting MKV to MP4...")
        self._mkv_to_mp4()

        # Convert MKV to point cloud sequence
        if self.debug:
            print("Converting MP4 to point cloud sequence...")
        pcd_sequence = self._mk4_to_point_cloud_sequence()

        # Process tracks
        if self.debug:
            print("Processing object tracks...")
        object_tracks = self._process_object_tracks()

        # Instantiate modules
        if self.debug:
            print("Instantiating modules...")

        # GSAM inference for initial frame
        if self.debug:
            print("Running GSAM inference...")
        video_path = self.input_path + "/" + self.video_name + ".mkv"
        masks, scores, logits, confidences, labels, input_boxes = self.gsam2.get_masks_video(self.object_names, video_path, frame=0)
        filtered_masks, filtered_labels = self.gsam2.filter_masks(masks, labels, self.num_objects)
        if self.debug:
            print("Labels:", filtered_labels)
            self.gsam2.visualize(video_path, masks, confidences, labels, input_boxes, frame=0)
            np.save(self.input_path + "/first_frame_mug_mask.npy", filtered_masks[0,0])
            # Save mask as PNG
            mask_image = filtered_masks[0,0] * 255  # Scale to 0-255
            cv2.imwrite(self.input_path + "/first_frame_mug_mask.png", mask_image)

        # Get the initial point cloud:
        if self.debug:
            print("Preparing initial point cloud...")
        initial_pcd, initial_pcd_seg = self.data_collector.prepare_pcd(filtered_masks, pcd_sequence[0], self.vis_threshold)
        if self.debug:
            print("Plotting initial point cloud...")
            plot_pcd(initial_pcd, initial_pcd_seg)

        # Detect movement:
        if self.debug:
            print("Detecting object movement...")
        indices, objects = self.data_collector.detect_movement(object_tracks, take_first_and_last=True)  # indices => video frames where object is stationary

        # Get transform sequence:
        if self.debug:
            print("Computing transform sequence...")
        transforms = self.data_collector.get_transform_sequence(indices, objects, object_tracks, pcd_sequence)

        # Save the data:
        if self.debug:
            print("Saving final data...")
        self.data_collector.save_final_data(initial_pcd, initial_pcd_seg, transforms, objects, mode = "train")

    def main_icp(self):
        """
        Performs point cloud registration using Iterative Closest Point (ICP) algorithm on video data.
        This method processes a video file to extract point clouds from the first and last frames,
        segments objects using groundtruth masks, and computes the transformation sequence between
        the initial and final point cloud configurations.
        The method follows these main steps:
        1. Converts video to point cloud sequence
        2. Extracts object masks from first frame
        3. Extracts object masks from last frame  
        4. Computes ICP transform sequence between initial and final frames
        5. Saves the registration results
        Requires:
            - Input video file (.mkv format) in self.input_path
            - Initialized GSAM2 segmentation model
            - DataCollector for point cloud processing
        Attributes modified:
            None - Results are saved via data_collector
        Returns:
            None
        Notes:
            - Currently assumes single object tracking (objects = [0])
            - Masks are filtered and eroded for better segmentation
            - Results are saved in "train" mode
        """

        video_path = self.input_path + "/" + self.video_name + ".mkv"
        
        # Convert MKV to point cloud sequence
        if self.debug:
            print("Converting MP4 to point cloud sequence...")
        pcd_sequence = self._mk4_to_point_cloud_sequence()
        
        # Find the object mask for the first frame
        masks, scores, logits, confidences, labels, input_boxes = self.gsam2.get_masks_video(self.object_names, video_path, frame=0)
        filtered_masks, filtered_labels = self.gsam2.filter_masks(masks, labels, self.num_objects)
        initial_pcd, initial_pcd_seg = self.data_collector.prepare_pcd(filtered_masks, pcd_sequence[0], self.vis_threshold)
        
        # Find the object mask for the last frame
        masks, scores, logits, confidences, labels, input_boxes = self.gsam2.get_masks_video(self.object_names, video_path, frame=len(pcd_sequence)-1)
        filtered_masks, filtered_labels = self.gsam2.filter_masks(masks, labels, self.num_objects)
        filtered_masks = self.gsam2.erode_masks(filtered_masks)
        final_pcd, final_pcd_seg = self.data_collector.prepare_pcd(filtered_masks, pcd_sequence[-1], self.vis_threshold)

        # Assumption: 1 object
        objects = [0]

        # Get transform sequence:
        if self.debug:
            print("Computing transform sequence...")
        
        transforms = self.data_collector.get_icp_transform_sequence(initial_pcd, final_pcd, initial_pcd_seg, final_pcd_seg, objects)
        # Save the data:
        if self.debug:
            print("Saving final data...")
        self.data_collector.save_final_data(initial_pcd, initial_pcd_seg, transforms, objects, mode = "train")


    def main_just_final(self):
        """
        Process a video to extract point cloud data and object segmentation for the final frame.
        This method performs the following steps:
        1. Converts an MKV video to a point cloud sequence
        2. Extracts object masks from the final frame using GSAM2
        3. Filters the masks based on specified number of objects
        4. Prepares the final point cloud with segmentation
        5. Saves the processed data
        Args:
            None (uses class instance variables)
        Class Requirements:
            - input_path (str): Path to input directory
            - video_name (str): Name of the video file without extension
            - debug (bool): Whether to show debug visualizations
            - gsam2: Instance of GSAM2 for mask generation
            - object_names (list): List of object names to detect
            - num_objects (int): Number of objects to track
            - vis_threshold: Threshold for visualization
            - data_collector: Instance of data collection class
        Returns:
            None. Saves processed data to disk via data_collector.save_final_data()
        Note:
            Currently assumes processing of a single object (objects = [0])
        """

        video_path = self.input_path + "/" + self.video_name + ".mkv"
        
        # Convert MKV to point cloud sequence
        if self.debug:
            print("Converting MP4 to point cloud sequence...")
        pcd_sequence = self._mk4_to_point_cloud_sequence()
        
        # Find the object mask for the last frame
        masks, scores, logits, confidences, labels, input_boxes = self.gsam2.get_masks_video(self.object_names, video_path, frame=len(pcd_sequence)-1)
        filtered_masks, filtered_labels = self.gsam2.filter_masks(masks, labels, self.num_objects)
        final_pcd, final_pcd_seg = self.data_collector.prepare_pcd(filtered_masks, pcd_sequence[-1], self.vis_threshold)

        if self.debug:
            # Plot combined masks
            import matplotlib.pyplot as plt
            combined_mask = np.zeros_like(masks[0,0])
            for i in range(len(masks)):
                combined_mask += masks[i,0]
            plt.figure(figsize=(10, 10))
            plt.imshow(combined_mask, cmap='gray')
            plt.colorbar()
            plt.title('Combined Masks')
            plt.savefig(os.path.join(self.input_path, 'combined_masks.png'))
            plt.show()
            plt.close()
            # import matplotlib.pyplot as plt
            # plt.figure(figsize=(10, 10))
            # plt.imshow(filtered_masks[0][0], cmap='gray')
            # plt.colorbar()
            # plt.title('Filtered Mask') 
            # plt.savefig(os.path.join(self.input_path, 'filtered_mask.png'))
            # plt.show()  # Add this line to display the plot
            # plt.close()
            print("Plotting initial point cloud...")
            plot_pcd(final_pcd, final_pcd_seg)

        # Assumption: 1 object
        objects = [0]

        # Get transform sequence:
        if self.debug:
            print("Computing transform sequence...")
        
        
        transforms = np.array([np.eye(4)])
        # Save the data:
        if self.debug:
            print("Saving final data...")
        self.data_collector.save_final_data(final_pcd, final_pcd_seg, transforms, objects, mode = "train")



    def main(self):
        if self.icp:
            self.main_icp()
        elif self.just_final:
            self.main_just_final()
        else:
            self.main_non_icp()


if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("--input_path", required=True, help="Path to the input video directory")
    parser.add_argument("--output_path", required=True, help="Path where the output data will be saved")
    parser.add_argument("--video_name", default="video", help="Name of the video file")
    parser.add_argument("--object_names", default="mug.", help="Space-separated string of object names, each ending with period")
    parser.add_argument("--num_objects", type=int, default=1, help="Number of objects to track")
    parser.add_argument("--device", default="cuda:1", help="Device to run computations on")
    parser.add_argument("--vis_threshold", type=float, default=1, help="Maximum distance threshold for point visibility")
    parser.add_argument("--debug", action="store_true", help="Enable debug mode")
    parser.add_argument("--icp", action="store_true", help="Use ICP+segmentation on each frame instead of Cotracker3 + RANSAC to infer the object transformation")
    parser.add_argument("--just_final", action="store_true", help="Only consider the final frame of the video for taxposed data generation")

    args = parser.parse_args()

    videototaxposed = VideoToTaxposed(
        input_path=args.input_path,
        output_path=args.output_path,
        video_name=args.video_name,
        object_names=args.object_names,
        num_objects=args.num_objects,
        device=args.device,
        vis_threshold=args.vis_threshold,
        icp=args.icp,
        debug=args.debug,
        just_final=args.just_final
    )
    videototaxposed.main()