from gsam_wrapper import GSAM2
from cotracker_wrapper import Cotracker3
from taxposed_data_collector import TaxPoseDDataCollector, plot_pcd
import torch
import argparse
import os
import numpy as np
from tqdm import tqdm
import gc
from pyk4a import PyK4APlayback, PyK4ACapture
from pyk4a.calibration import CalibrationType, Calibration
import subprocess

class VideoToTaxposed:
    """
    Assumptions:
    1. The input path contains a video in mk4 format, containing rgb, depth and intrinsics information. This can be captured e.g. using the module PyK4A (see capture_video.py)
    """
    def __init__(self,
                 input_path, # "assets/videos/table_bussing_four_objects"
                 output_path, # "assets/data/table_bussing_four_objects"
                 video_name="video.mkv",
                 object_names="mug.", # "blue plate. pink plate. red bowl. white cup"
                 num_objects=1, # mug
                 device="cuda:1",
                 vis_threshold=1.,
                 debug=False):
        """ Initialize the VideoToTaxposed class.
            Args:
                input_path (str): Path to the input video directory and subsequent data generated by the class if in debug mode
                output_path (str): Path where the output data will be saved
                video_name (str, optional): Name of the video file. Defaults to "video.mkv"
                object_names (str, optional): Space-separated string containing object names to track. Each name should end with period. Defaults to "mug."
                num_objects (int, optional): Number of objects to track. Defaults to 1
                device (str, optional): Device to run computations on. Defaults to "cuda:1"
                debug (bool, optional): Enable debug mode. Defaults to False
            Attributes:
                vis_threshold (float): Maximum distance (in meters) threshold for point visibility. Points further than this distance from camera are removed
            Note:
                The object_names string should have exactly num_objects names, each ending with a period.
                Example: "blue plate. pink plate. red bowl." for num_objects=3
        """
        self.input_path = input_path
        self.output_path = output_path
        self.video_name = video_name
        self.object_names = object_names
        self.num_objects = num_objects
        self.device = device
        self.gsam2 = GSAM2(self.device)
        self.vis_threshold = vis_threshold # All points further than this distance from the camera are removed
        self.debug = debug


    def _mk4_to_point_cloud_sequence(self):
        """
        Convert an MKV video file captured from a Kinect v4 camera into a sequence of point clouds.

        This method processes a recorded MKV video file frame by frame, extracting the depth
        information from each frame to generate 3D point clouds. The point clouds 
        are stored sequentially in a numpy array.

        Returns:
            np.ndarray: A sequence of point clouds, where each point cloud contains 3D coordinates
                   for each point. Shape is (height, width, n_points, 3), where the
                   last dimension contains [x, y, z] values.
        Raises:
            EOFError: When reaching the end of the video file.

        Note:
            - The input MKV file must be located at self.input_path/self.video_name
            - Frames where depth data is missing are skipped
            - Points beyond self.vis_threshold meters from camera are filtered out
        """
        pcd_sequence = []
        k4a = PyK4APlayback(self.input_path + "/" + self.video_name)
        k4a.open()
        
        try:
            while True:
                # Get next frame
                capture = k4a.get_next_capture()
                
                # Skip frames with missing data
                if capture.depth is None or capture.color is None:
                    continue

                # Convert depth image to 3D points
                points_3d = capture.transformed_depth_point_cloud

                # Convert points from millimeters to meters
                points_3d = points_3d.astype(np.float32) / 1e3          # Convert to meters

                # Remove invalid points (where depth is 0 or beyond threshold)
                valid_points = np.logical_and(points_3d[:, :, 2] > 0, points_3d[:, :, 2] < self.vis_threshold)
                points_3d[~valid_points] = 0
                
                # colors = capture.color.reshape(-1, 3).astype(float) / 255.0
                
                # Create point cloud with xyz and rgb values
                # point_cloud = np.concatenate([points_3d, colors], axis=1)
                point_cloud = points_3d
                pcd_sequence.append(point_cloud)
            
        except EOFError:
            print("Reached end of video file")
        finally:
            k4a.close()
            
        return np.array(pcd_sequence)
    
    def _mkv_to_mp4(self):
        """
        Convert an MKV video file to MP4 format using FFmpeg.

        This method uses FFmpeg to convert the input MKV video file to MP4 format while preserving
        the video stream and using the H.264 codec. The output file will be saved in the same
        directory as the input file.

        Returns:
            None

        Raises:
            subprocess.CalledProcessError: If the FFmpeg conversion process fails.

        Note:
            - Requires FFmpeg to be installed on the system
            - Only copies the video stream (stream 0:0) and ignores audio tracks
            - Output filename will have the same name as input but with .mp4 extension
        """
        input_path = self.input_path + "/" + self.video_name
        output_path = self.input_path + "/" + self.video_name.replace(".mkv", ".mp4")

        # if self.debug:
        #     command = ['ffmpeg', '-i', input_path, '-map', '0:0', '-c:v', 'libx264', output_path]   
        # else:
        #     command = ['ffmpeg', '-y', '-hide_banner', '-loglevel', 'error', '-i', input_path, '-map', '0:0', '-c:v', 'libx264', output_path]

        command = ['ffmpeg', '-y', '-hide_banner', '-loglevel', 'error', '-i', input_path, '-map', '0:0', '-c:v', 'libx264', output_path]
        subprocess.run(command, check=True)

    def _process_object_tracks(self):
        """
        This method takes a video and object information to generate object tracks. It uses GSAM for mask 
        generation and Cotracker for tracking objects throughout the video sequence.

        Parameters
        ----------
        None : Uses instance attributes
            self.input_path : str
                Path to input directory
            self.video_name : str
                Name of the video file
            self.debug : bool
                Flag for debug mode
            self.object_names : list
                Names of objects to track
            self.frame : int
                Frame number to process
            self.num_objects : int
                Number of objects to track
            self.device : str
                Device to run inference on ('cpu' or 'cuda')

        Returns
        -------
        list
            List of numpy arrays containing predicted tracks for each object.
            Each track array has shape (num_frames, num_points, 2) containing xy coordinates.

        Notes
        -----
        If debug mode is enabled, tracks will be saved in the input directory under 'tracks_' folder.
        """
        video_path = self.input_path + "/" + self.video_name
        if self.debug:
            tracks_path = self.input_path
            os.makedirs(tracks_path, exist_ok=True)

        # Instantiate modules
        cotracker3 = Cotracker3(self.device)

        # GSAM inference
        masks, scores, logits, confidences, labels, input_boxes = self.gsam2.get_masks(self.object_names, video_path, 0)
        filtered_masks, _ = self.gsam2.filter_masks(masks, labels, self.num_objects)

        # Cotracker inference
        all_tracks = []
        filtered_masks = filtered_masks[:, 0]
        for i in range(filtered_masks.shape[0]):
            pred_tracks = cotracker3.get_tracks(video_path, filtered_masks[i])
            pred_tracks = pred_tracks.cpu().detach().numpy()
            if self.debug:
                # np.save(tracks_path + "/" + str(i) + ".npy", pred_tracks)
                np.save(tracks_path + "/" + "tracks" + ".npy", pred_tracks)
            all_tracks.append(pred_tracks)
        return all_tracks

    def main(self):
        # Convert MKV to MP4
        if self.debug:
            print("Converting MKV to MP4...")
        self._mkv_to_mp4()

        # Convert MP4 to point cloud sequence
        if self.debug:
            print("Converting MP4 to point cloud sequence...")
        pcd_sequence = self._mk4_to_point_cloud_sequence()

        # Process tracks
        if self.debug:
            print("Processing object tracks...")
        object_tracks = self._process_object_tracks()

        # Instantiate modules
        if self.debug:
            print("Instantiating modules...")

        data_collector = TaxPoseDDataCollector(self.output_path)

        # GSAM inference for initial frame
        if self.debug:
            print("Running GSAM inference...")
        video_path = self.input_path + "/" + self.video_name
        masks, scores, logits, confidences, labels, input_boxes = self.gsam2.get_masks(self.object_names, video_path, frame=0)
        filtered_masks, filtered_labels = self.gsam2.filter_masks(masks, labels, self.num_objects)
        if self.debug:
            print("Labels:", filtered_labels)
            self.gsam2.visualize(video_path, masks, confidences, labels, input_boxes, frame=0)

        # Get the initial point cloud:
        if self.debug:
            print("Preparing initial point cloud...")
        initial_pcd, initial_pcd_seg = data_collector.prepare_initial_pcd(filtered_masks, pcd_sequence[0], self.vis_threshold)
        if self.debug:
            print("Plotting initial point cloud...")
            plot_pcd(initial_pcd, initial_pcd_seg)

        # Detect movement:
        if self.debug:
            print("Detecting object movement...")
        indices, objects = data_collector.detect_movement(object_tracks)  # indices => video frames where object is stationary

        # Get transform sequence:
        if self.debug:
            print("Computing transform sequence...")
        transforms = data_collector.get_transform_sequence(indices, objects, object_tracks, pcd_sequence)

        # Save the data:
        if self.debug:
            print("Saving final data...")
        data_collector.save_final_data(initial_pcd, initial_pcd_seg, transforms, objects, mode = "train")


if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("--input_path", required=True, help="Path to the input video directory")
    parser.add_argument("--output_path", required=True, help="Path where the output data will be saved")
    parser.add_argument("--video_name", default="video.mkv", help="Name of the video file")
    parser.add_argument("--object_names", default="mug.", help="Space-separated string of object names, each ending with period")
    parser.add_argument("--num_objects", type=int, default=1, help="Number of objects to track")
    parser.add_argument("--device", default="cuda:1", help="Device to run computations on")
    parser.add_argument("--vis_threshold", type=float, default=1, help="Maximum distance threshold for point visibility")
    parser.add_argument("--debug", action="store_true", help="Enable debug mode")

    args = parser.parse_args()

    videototaxposed = VideoToTaxposed(
        input_path=args.input_path,
        output_path=args.output_path,
        video_name=args.video_name,
        object_names=args.object_names,
        num_objects=args.num_objects,
        device=args.device,
        vis_threshold=args.vis_threshold,
        debug=args.debug
    )
    videototaxposed.main()